### ISSUE TITLE
Impossible de terminer l'installation de snowboy lors de l'installation de OpenJarvis

### ISSUE THREAD

**Issue by Calypso514** [alexylem/jarvis#1000]
Bonjour à tous,

Alors voilà,
Je suis en train de fabriquer un miroir magique qui fonctionne grâce à MagicMirror. J'aimerais y intégrer l'assistant vocal OpenJarvis mais à la fin de l'installation de celui-ci, je dois installer snowboy mais je ne parviens pas à finaliser son installation, je reçois le message d'erreur suivant : 

```
Traceback (most recent call last):
  File "get-pip.py", line 24244, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "/tmp/tmpTcbW8a/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax

```

Quelqu'un sait-il à quoi cela est du et comment régler mon problème ?

Merci d'avance
![192 168 0 35 (raspberrypi) - VNC Viewer 14_02_2021 15_14_24](https://user-images.githubusercontent.com/79049351/107879357-a844bb00-6ed8-11eb-806e-90e13db24b4f.png)

**Comment by professeurmordicus** [comment]
Snowboy ferme ses portes. Quelqu'un essaye de trouver des solutions, mais je ne suis pas sûr de comprendre ce qui marche ou non pour l'instant...

https://github.com/ferrader/openjarvis_nextgen/issues/1

**Comment by Calypso514** [comment]
Je viens de voir ça, quel dommage!
Mais j'ai aussi lu que la page github restait ouverte je devrais donc pouvoir le télécharger, non?

**Comment by knops-ch** [comment]
Salut, 
dans ~/jarvis/stt_engines/snowboy

edite : main.sh (nano main.sh)
Commente : 
wget https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/$binaries.tar.bz2
>
#wget https://s3-us-west-2.amazonaws.com/snowboy/snowboy-releases/$binaries.tar.bz2

et copie à la place : 
wget https://s3-us-west-2.amazonaws.com/snowboy2/snowboy-releases/$binaries.tar.bz2

voir : Precompiled Binaries with Python Demo
du fork : https://github.com/seasalt-ai/snowboy

Cela  fonctionné pour moi, par contre, tu seras bloqués à la création du model personnel, le service Snowboy étant arrêté.
