### ISSUE TITLE
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#33]
```
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.5 1% 1 0.5 1% trim 0 10
```

**Comment by alexylem** [comment]
Ce problème arrive lorsque la fonction d'enregistrement détecte un son, commence à l'enregistrer, mais ne détecte pas de silence dans les 10 secondes.
Cela peut arriver dans les cas suivants:
* Bruits de fond (télé, discussions...)
* Pas assez d'espace entre les commandes vocales
* Micro trop sensible (baisse la sensibilité dans Settings > Audio > Sensitivity, attention à #26 )

Vérifier avant tout que votre micro fonctionne bien en suivant les étapes de configuration dans Settings > Step-by-Step Wizard)

**Comment by chilbin** [comment]
ok je vais essayer merci

**Comment by Figouze** [comment]
J'ai essayé d'utiliser snowboy à la place mais j'ai d'autres erreurs.

```
ninou@fixe:~/jarvis$ ./jarvis.sh 
Checking for updates...[Up-to-date]

------- Config (verbose) -------
platform              linux 
language              fr_FR 
play_hw               hw:0,0 
rec_hw                hw:0,0 
trigger_stt           snowboy 
command_stt           pocketsphinx 
tts_engine            espeak 
google_speech_api_key  
--------------------------------

r2: Bonsoir ninou
r2: Waiting to hear 'r2'
ninou: (listening...)
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 1, in <module>
    import snowboydecoder
  File "/home/ninou/jarvis/stt_engines/snowboy/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/ninou/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/ninou/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: /home/ninou/jarvis/stt_engines/snowboy/_snowboydetect.so: cannot open shared object file: No such file or directory
ERROR: snowboy recognition failed

```

**Comment by alexylem** [comment]
As-tu bien suivi les étapes d'installation de `snowboy` en le sélectionnant?
Est-ce que le fichier suivant existe bien?
```
/home/ninou/jarvis/stt_engines/snowboy/_snowboydetect.so
```

**Comment by Figouze** [comment]
Oui; il est bien sélectionné dans settings.
Je veux bien le réinstaller s'il le faut. Je ne sais pas comment le réinstaller (aptitude reinstall ?)


Voilà pour le fichier
```
ninou@fixe:~/jarvis/config$ ls -l /home/ninou/jarvis/stt_engines/snowboy/_snowboydetect.so
-rwxr-xr-x 1 ninou ninou 691052 mai   24 20:34 /home/ninou/jarvis/stt_engines/snowboy/_snowboydetect.so

```

**Comment by alexylem** [comment]
Tu es sur raspberry pi?

**Comment by Figouze** [comment]
Non, pour le moment, un pc fixe sous debian

**Comment by alexylem** [comment]
Voila le problème, les librairies `snowboy` que j'utilise sont pré-compilées pour OSX et Raspberry Pi.
Donc à moins d'essayer de compiler la tienne (si tu veux vraiment rester sur ton PC, va sur leur site pour suivre les instructions), il vaut mieux attendre de passer sous Raspberry Pi ou retourner à PocketSphinx...

**Comment by Figouze** [comment]
Bien, sur pocketsphynx, j'ai l'erreur citée plus haut quel que soit le niveau de micro, etc..
Les tests de configuration fonctionnent (micro et écote) mais pas le reste.
Le mode conversation clavier fonctionne.
(Merci pour le support au passage).

```
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.5 1% 1 0.5 1% trim 0 10
```

**Comment by alexylem** [comment]
```
play_hw               false 
rec_hw                false
```
Il ne semble que tu n'a pas fait la configuration enceintes et micro.
Peux-tu vérifier que les 2 fonctionnent bien dans Settings > Step-by-Step Wizard?

**Comment by Figouze** [comment]
Il y a bien indiqué false.
J'ai pourtant testé le micro et les écouteurs dans settings et cela fonctionne correctement.

Les écouteurs me retournent ma voix avec jarvis, une fois sur 30... peut-être quand il me met :SEE(listening...)



```

ninou@fixe:~/jarvis$ ./jarvis.sh 
Checking for updates...[Up-to-date]

applause.wav:

 File Size: 463k      Bit Rate: 1.41M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:02.62  

In:100%  00:00:02.62 [00:00:00.00] Out:116k  [      |      ] Hd:0.0 Clip:0    
Done.
true

applause.wav:

 File Size: 463k      Bit Rate: 1.41M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 44100Hz      
Replaygain: off         
  Duration: 00:00:02.62  

In:100%  00:00:02.62 [00:00:00.00] Out:116k  [      |      ] Hd:0.0 Clip:0    
Done.
true

Input File     : 'default' (alsa)
Channels       : 2
Sample Rate    : 48000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.07 [00:00:00.00] Out:144k  [      |      ] Hd:0.0 Clip:0    
Done.

jarvis-record.wav:

 File Size: 576k      Bit Rate: 1.54M
  Encoding: Signed PCM    
  Channels: 2 @ 16-bit   
Samplerate: 48000Hz      
Replaygain: off         
  Duration: 00:00:03.00  

In:100%  00:00:03.00 [00:00:00.00] Out:144k  [      |      ] Hd:0.0 Clip:0    
Done.
true

------- Config (verbose) -------
platform              linux 
language              fr_FR 
play_hw               false 
rec_hw                false 
trigger_stt           pocketsphinx 
command_stt           pocketsphinx 
tts_engine            svox_pico 
google_speech_api_key  
--------------------------------

jarvis: Bonjour ninou
jarvis: Waiting to hear 'jarvis'
ninou: (listening...)
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 45 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 13 (10 = 1 sec)
?(listening...)
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 27 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 27 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 100 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 33 (10 = 1 sec)
DEBUG: too long for a trigger (min 0.5 max 1.5 sec), ignoring...
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 00 (10 = 1 sec)
DEBUG: too short for a trigger (min 0.2 max 1.5 sec), ignoring...
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10
DEBUG: speech duration was 05 (10 = 1 sec)
SEE(listening...)
rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little jarvis-record.wav silence 1 0.1 1% 1 0.5 1% trim 0 10

```

**Comment by alexylem** [comment]
Ok il a donc réussi à décoder "SEE" dans ce que tu as dit. Mais pas "JARVIS".
Dans les logs ci-dessus, je vois que tu n'as pas pas le problème du timeout de 10 secondes à cause du bruit (1,6 secondes, 2 secondes, 3 secondes). Je ferme donc ce ticket.

Essayes donc de prononcer "JARVIS" de manière à ce que le son de ta voix dure entre 0.2 et 1.5 secondes comme conseillé.
Et je te conseille aussi d'ajuster la sensibilité de ton micro si nécessaire, pour d'autres ca a aidé.
```
alsamixer
```
