### ISSUE TITLE
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Lins59** [alexylem/jarvis#338]
Hello,

Je rencontre cette erreur quand j'essaye de démarrer Jarvis (même si j'ai sélectionné : "Pas de microphone", il m'a quand même installé Snowboy ;-) )
```shell
~/jarvis$ ./jarvis.sh

------------ Config ------------
jv_version           17.01.07
jv_arch              armv6l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              false
rec_hw               false
speaker              Default
microphone           Default
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
snowboy: Hello
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*
snowboy: Waiting to hear 'snowboy'
Maitre: (listening...)
DEBUG: models=alexa,snowboy
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 1, in <module>
    import snowboydecoder
  File "/home/george/jarvis/stt_engines/snowboy/snowboydecoder.py", line 5, in <module>
    import snowboydetect
  File "/home/george/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/george/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
DEBUG: modelid=-10
ERROR: snowboy recognition failed
DEBUG: program exit handler
DEBUG: program_exit hook
```

Merci en tout cas pour ce programme 👍

**Comment by Lins59** [comment]
~/jarvis$ python -V
Python 2.7.9

**Comment by Lins59** [comment]
Il faut installer ce paquet :
apt-get install libpython2.7

Ca a eu l'air de résoudre le problème.

A installer de base ?

Bonne journée !

**Comment by alexylem** [comment]
Pas d'après la documentation snowboy.
C'est la première fois que ce problème est remonté, on dirait qu'il te manquait cette librairie sur ta distribution Raspberry Pi.
Merci en tout cas pour avoir partagé la solution!
