### ISSUE TITLE
Problème de reconnaissance

### ISSUE THREAD

**Issue by jarvisaide** [alexylem/jarvis#502]
Bonjour,

J'ai un problème de reconnaissance avec Jarvis. Voici mon troubleshot 

```
------------ Config ------------
jv_branch            master
jv_version           17.03.25
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        8
language             fr_FR
play_hw              false
rec_hw               false
speaker              Default
microphone           Default
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
Alexa: Hello
DEBUG: start_speaking hook
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Alexa: Waiting to hear 'Alexa'
vincent: (listening...)
DEBUG: models=alexa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 66, in <module>
    trigger_ticks=trigger_ticks)
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder.py", line 88, in __init__
    stream_callback=audio_callback)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid sample rate] -9997
DEBUG: modelid=-10
ERROR: snowboy recognition failed

DEBUG: program_exit hook
```

Merci de vos retours
Thomas

**Comment by alexylem** [comment]
Dupplicate: #311 
Peux-tu voir si tu y trouves ta solution, sinon réouvrir #311 pour y indiquer le matériel que tu utilises?
Merci.
