### ISSUE TITLE
EOFError with Snowboy

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#553]
```shell
Jarvis: Waiting to hear 'Jarvis'
Alex: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [-1, -1, -1, -1]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 76, in record_proc
    wav = wave.open(process.stdout, 'rb')
  File "/usr/lib/python2.7/wave.py", line 509, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/wave.py", line 129, in initfp
    self._file = Chunk(file, bigendian = 0)
  File "/usr/lib/python2.7/chunk.py", line 63, in __init__
    raise EOFError
EOFError
```

**Comment by sparkphp** [comment]
Depuis aujourd'hui et à priori la récupération d'une mise à jour de Jarvis, l'exécution bloque dès la reconnaissance du hotword avec snowboy:

jarvis: Waiting to hear 'jarvis'
philip: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 90, in record_proc
    wav = wave.open(process.stdout, 'rb')
  File "/usr/lib/python2.7/wave.py", line 509, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/wave.py", line 129, in initfp
    self._file = Chunk(file, bigendian = 0)
  File "/usr/lib/python2.7/chunk.py", line 63, in __init__
    raise EOFError
EOFError

@alexylem j'ai vu que tu avais repéré ce soucis depuis déjà Avril dernier, sais-tu quelle en est la cause?

D'avance merci pour un retour.

**Comment by BlkWolfLH** [comment]
Greetings all. I was wondering if anything has been found to address this issue? It has recently shown up for myself where the project has been working great up till this point. I have taken my install back to original config and still have the same error. 

I tested to see if the audio device was locked due to use and that was not the issue.

Upon further investigation I found that my home directory's .asoundrc file was reset to default. This resulted in producing an error when jarvis starts

  "cat: /proc/asound/carde/id: No such file or directory"

Checking the file location I found I do not have any directory by the name "carde". Restoring a copy of my .asoundrc and pointing to the correct USB devices addressed this issue for me. 

Hope it helps.

**Comment by alex-randles** [comment]
Hi,

I was having the same issue I fixed it by adding os.system("killall arecord") on below line 90 in snowboydecoder_arecord.py. I believe chunks coming in from a different arecord process are causing the error.

```
    def record_proc(self):
        os.system("killall arecord")
        CHUNK = 1024
        RECORD_RATE = 16000
```
