### ISSUE TITLE
Installation automatique de Snowboy sur OSMC

### ISSUE THREAD

**Issue by loteran** [alexylem/jarvis#628]
Bonjour à tous,
Je ne parviens pas à installer snowboy correctement, enfin je pense ;)

J'ai donc installer jarvis sur mon raspi3 version OSMC (permet d'avoir kodi avec un fonctionnement optimal, trop de probleme avec raspbian et domotique)
```
osmc@osmc:~/jarvis/stt_engines/snowboy$ lsb_release -ds
Debian GNU/Linux 8.8 (jessie)
```
```
nano /etc/issue
OSMC: Open Source Media Center \n \l
```

Jusque la tout fonctionne bien (enfin presque), j'utilise Bing pour la reconnaissance vocale et lorsque j'utilise un mot avec un accent, il n'est pas reconnu.

Exemple : dans le plugin freebox player, il y a la commande ALLUME LA TELE, lorsque je dis "allume la télé", jarvis recopie le texte "allume la télé" mais me dis qu'il ne comprend pas, j'ai donc modifié la commande par "allume la box" et la aucun soucis, même problème avec ETEIN, bing reconnais éteins mais jarvis ne reconnait pas, je remplace ETEIN par FERME et la ça fonctionne ...

Avez vous le même problème ?

A la vue de ce problème je me suis dis que j'allais utiliser Snowboy afin d'enregistrer moi meme mes commandes, sauf que lorsque j'essai de l'installer par jarvis, rien ne s'installe, il recherche les dépendances et s’arrête  
```
1/2 Preparation of dependencies
osmc@osmc:~/jarvis/stt_engines/snowboy$
```
, sachant qu'elles sont toutes installées, puisque j'ai installé snowboy manuellement par la suite et ai retenté l'installation par jarvis.

Avec npm, j'ai tenté de l'installer après avoir installé et mis à jour toutes les dépendances node.js, npm...

`sudo npm install --save snowboy`

```
> snowboy@1.2.0 preinstall /node_modules/snowboy
> npm install node-pre-gyp

npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EACCES: EACCES: permission denied, open '/root/.npm/_cacache/tmp/79ad3d41'
npm notice created a lockfile as package-lock.json. You should commit this file.
added 112 packages in 18.995s

┌───────────────────────────────────────────────────┐
│              npm update check failed              │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘

> snowboy@1.2.0 install /node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v51-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.2.0 and node@7.10.0 (node-v51 ABI) (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/7.10.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/node_modules/snowboy/.node-gyp"
make: Entering directory '/node_modules/snowboy/build'
make: *** No rule to make target '../.node-gyp/7.10.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/node_modules/snowboy/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/osmc/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.27-9-osmc
gyp ERR! command "/home/osmc/.nvm/versions/node/v7.10.0/bin/node" "/home/osmc/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/node_modules/snowboy/lib/node/binding/Release/node-v51-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/node_modules/snowboy/lib/node/binding/Release/node-v51-linux-arm"
gyp ERR! cwd /node_modules/snowboy
gyp ERR! node -v v7.10.0
gyp ERR! node-gyp -v v3.6.1
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/home/osmc/.nvm/versions/node/v7.10.0/bin/node /home/osmc/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/node_modules/snowboy/lib/node/binding/Release/node-v51-linux-arm/snowboy.node --module_name=snowboy --module_path=/node_modules/snowboy/lib/node/binding/Release/node-v51-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/node_modules/snowboy/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Linux 4.4.27-9-osmc
node-pre-gyp ERR! command "/home/osmc/.nvm/versions/node/v7.10.0/bin/node" "/node_modules/snowboy/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /node_modules/snowboy
node-pre-gyp ERR! node -v v7.10.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute '/home/osmc/.nvm/versions/node/v7.10.0/bin/node /home/osmc/.nvm/versions/node/v7.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/node_modules/snowboy/lib/node/binding/Release/node-v51-linux-arm/snowboy.node --module_name=snowboy --module_path=/node_modules/snowboy/lib/node/binding/Release/node-v51-linux-arm' (1)
npm WARN enoent ENOENT: no such file or directory, open '/package.json'
npm WARN !invalid#1 No description
npm WARN !invalid#1 No repository field.
npm WARN !invalid#1 No README data
npm WARN !invalid#1 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the snowboy@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-06-02T13_37_41_471Z-debug.log
osmc@osmc:/$
```
Je vois que dans le script il télécharge les fichiers de snowboy, sauf que [la page n'existe plus : ](https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.2.0/Release/snowboy-v1.2.0-node-v51-linux-arm.tar.gz)
 

J'ai donc tenté de l'installer manuellement et visiblement l'installation s'est faite, non sans mal, mais lorsque je relance jarvis il me dit que snowboy n'est pas installé.

une petite aide ?
Merci d'avance ;)

**Comment by oeildefeu** [comment]
Bonjour,
pour moi le lien de téléchargement fonctionne bien .. :-/

**Comment by loteran** [comment]
Oui effectivement, pi-hole bloquait le liens.
Donc nouvel essai avec l’accès au download (shame on me 👎 ) , ce coup ci l'install se fait bien mais lorsque je relance jarvis il me dit que snowboy n'est pas installé, or lorsque je relance l'installation de snowboy par npm, il me dit qu'il est déjà installé : 

```
osmc@osmc:~$ npm install --save snowboy

> snowboy@1.2.0 preinstall /home/osmc/node_modules/snowboy
> npm install node-pre-gyp

added 112 packages in 22.991s

> snowboy@1.2.0 install /home/osmc/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

[snowboy] Success: "/home/osmc/snowboy/lib/node/binding/Release/node-v51-linux-arm/snowboy.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN saveError ENOENT: no such file or directory, open '/home/osmc/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/home/osmc/package.json'
npm WARN osmc No description
npm WARN osmc No repository field.
npm WARN osmc No README data
npm WARN osmc No license field.
npm WARN osmc Invalid dependency: glob undefined
npm WARN osmc Invalid dependency: minimatch undefined
npm WARN osmc Invalid dependency: npmlog undefined
npm WARN osmc Invalid dependency: readable-stream undefined
npm WARN osmc Invalid dependency: wide-align undefined

updated 1 package in 32.233s
osmc@osmc:~$
```
et lorsque je lance l'installation de snowboy par jarvis, il me fait comme avant, il recherche les dépendances 1/2 et s’arrête...

Je sais plus quoi faire ^^

**Comment by alexylem** [comment]
@loteran Jarvis cherche la présence du fichier:
```
jarvis/stt_engines/snowboy/_snowboydetect.so
```
Qui est nécessaire pour le bon fonctionnement de Jarvis avec snowboy.
Je ne sais pas trop comment tu as installé snowboy mais ceci doit être la cause 😄

**Comment by loteran** [comment]
Merci de ton retour Alex, pour l'installation de snowboy, je suis passé par NPM comme indiqué sur mon post au dessus
`npm install --save snowboy`

Voici ce qui se trouve dans le répertoire de snowboy dans jarvis
```
osmc@osmc:~$ cd jarvis/stt_engines/snowboy/
osmc@osmc:~/jarvis/stt_engines/snowboy$ ls
Snowboy.pm   main.py         maindecoder_sox.py      snowboy-detect-swig.o
Snowboy.so   main.sh         maindecoder_sox.pyc     snowboy-detect.i
jarvis.pmdl  maindecoder.py  snowboy-detect-swig.cc  uninstall.sh
osmc@osmc:~/jarvis/stt_engines/snowboy$
```
Effectivement il n'y a pas de _snowboydetect.so

J'ai également lancé une installation avec les fichiers de snowboy pris sur github : 

`osmc@osmc:~/snowboy$ sudo python setup.py install`
```
running install
running bdist_egg
running egg_info
creating snowboy.egg-info
writing requirements to snowboy.egg-info/requires.txt
writing snowboy.egg-info/PKG-INFO
writing top-level names to snowboy.egg-info/top_level.txt
writing dependency_links to snowboy.egg-info/dependency_links.txt
writing manifest file 'snowboy.egg-info/SOURCES.txt'
reading manifest file 'snowboy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.txt'
warning: no previously-included files found matching '*.pyc'
writing manifest file 'snowboy.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/snowboy
copying examples/Python/__init__.py -> build/lib.linux-armv7l-2.7/snowboy
copying examples/Python/snowboydecoder.py -> build/lib.linux-armv7l-2.7/snowboy
copying examples/Python/snowboydetect.py -> build/lib.linux-armv7l-2.7/snowboy
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/snowboy
copying build/lib.linux-armv7l-2.7/snowboy/__init__.py -> build/bdist.linux-armv7l/egg/snowboy
copying build/lib.linux-armv7l-2.7/snowboy/snowboydecoder.py -> build/bdist.linux-armv7l/egg/snowboy
copying build/lib.linux-armv7l-2.7/snowboy/snowboydetect.py -> build/bdist.linux-armv7l/egg/snowboy
byte-compiling build/bdist.linux-armv7l/egg/snowboy/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-armv7l/egg/snowboy/snowboydecoder.py to snowboydecoder.pyc
byte-compiling build/bdist.linux-armv7l/egg/snowboy/snowboydetect.py to snowboydetect.pyc
installing package data to build/bdist.linux-armv7l/egg
running install_data
copying README.md -> build/bdist.linux-armv7l/egg/.
creating build/bdist.linux-armv7l/egg/snowboy/resources
copying resources/common.res -> build/bdist.linux-armv7l/egg/snowboy/resources
copying resources/ding.wav -> build/bdist.linux-armv7l/egg/snowboy/resources
copying resources/dong.wav -> build/bdist.linux-armv7l/egg/snowboy/resources
copying resources/snowboy.wav -> build/bdist.linux-armv7l/egg/snowboy/resources
copying resources/snowboy.umdl -> build/bdist.linux-armv7l/egg/snowboy/resources
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying snowboy.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying snowboy.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying snowboy.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying snowboy.egg-info/not-zip-safe -> build/bdist.linux-armv7l/egg/EGG-INFO
copying snowboy.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying snowboy.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
creating dist
creating 'dist/snowboy-1.2.0-py2.7.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing snowboy-1.2.0-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/snowboy-1.2.0-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/snowboy-1.2.0-py2.7.egg
Extracting snowboy-1.2.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
snowboy 1.2.0 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/snowboy-1.2.0-py2.7.egg
Processing dependencies for snowboy==1.2.0
Searching for PyAudio==0.2.8
Best match: PyAudio 0.2.8
Adding PyAudio 0.2.8 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for snowboy==1.2.0
```
En regardant dans mon repertoire d'installation de snowboy, j'ai trouvé _snowboydetect.so dans lequel il n'y a rien, je l'ai ajouté à jarvis/sstt_engines/snowboy

La jarvis ne me propose plus de l'installer mais j'obtient une erreur : 

```
jarvis: Waiting to hear 'jarvis'
axel: ERROR: snowboy recognition failed
HELP: run in troubleshooting mode for more information
```

Sachant que j'ai placé jarvis.pdml dans un répertoire que j'ai créer (resources) car jarvis recherche dans jarvis/sstt_engines/snowboy/resources et j'obtient l'erreur du dessus.

J'ai donc tout supprimer pour re-tenter une install par jarvis et j'obtiens : 

```
1/2 Preparation of dependencies
osmc@osmc:~/jarvis/stt_engines/snowboy$
```
Je n'en comprends pas la raison...

**Comment by alexylem** [comment]
Tu es sur raspberry pi? Si oui tu devrais en effet utiliser l'install via Jarvis.
Si ca s'est stoppé à Preparation of dependencies c'est que tu as du avoir un message d'erreur, surement:
```
Pre-packaged Snowboy binaries only available for:
- Rasbpian 8 Jessie on Raspberry Pi
- Ubuntu 12.04 and 14.04 on x86 64bits
- Mac OS X
Please use correct distribution or compile your own version of Snowboy:
https://github.com/kitt-ai/snowboy
```
Tu confirmes?
Le mieux c'est un petit asciinema:
```shell
sudo apt-get install -y asciinema && asciinema rec # start session recording
jarvis
Ctrl+D # stop recording
y # yes to upload and get URL to paste here
```

**Comment by loteran** [comment]
Oui je suis bien sur raspberry pi3 avec OSMC et domoticz.

Voici le lien pour la [video](http://asciinema.org/a/5c8zjl1r0elz12pacxrypymbo)

Merci de ton aide.

**Comment by alexylem** [comment]
@loteran c'est bien ce que je pensais. En fait ca ne passe pas car comme le dit le message d'erreur tu dois être sur Jessie (et tu es sur OSMC). Tu peux toujours essayer de récupérer le package pré-compilé pour Jessie à la main sur le site de snowboy et voir si il marche:
http://docs.kitt.ai/snowboy/#downloads
Sinon il faudra suivre les instructions et compiler toi même:
https://github.com/kitt-ai/snowboy#precompiled-binaries-with-python-demo

**Comment by alexylem** [comment]
Si le package de Jessie marche sur OSMC dit moi et j'adapterai le code de l'installeur.

**Comment by loteran** [comment]
Oui je me doutais que ça venais de là, mais ce qui est étonnant c'est que
je suis sur jessie, quand je vérifie ma distribution il est bien indiqué
jessie et pour la compilation à la main, c'est ce que j'ai indiqué au
dessus, je l'ai installé en le compilant et également par npm il s'installe
correctement mais quand je lance jarvis il me dis qu'il n'est pas installé
car il ne trouve pas le fichier snowboydetect et si j'en mais un cela
plante... Ps osmc c'est une image de jessie qui boot sur kodi

**Comment by loteran** [comment]
Ok, donc j'ai tout remis à plat et suis repartis d'une installation toute fraiche de jarvis, je confirme que ma version étant nommée OSMC, elle n'est pas reconnue par jarvis, mais c'est bien une jessie.
`apt-cache policy libc6`

`
libc6:
  Installed: 2.19-18+deb8u9
  Candidate: 2.19-18+deb8u9
  Version table:
 *** 2.19-18+deb8u9 0
        500 http://ftp.debian.org/debian/ jessie/main armhf Packages
        100 /var/lib/dpkg/status
     2.19-18+deb8u3 0
        500 http://security.debian.org/ jessie/updates/main armhf Packages`

`$ uname -a`

`Linux osmc 4.9.29-4-osmc #1 SMP PREEMPT Tue May 30 19:42:56 UTC 2017 armv7l GNU/Linux`

`$ nano /etc/debian_version` ---> 8.8

Donc après avoir copié les fichiers pré-compilés dans le repertoire snowboy, tout c'est mis à fonctionner.

Merci Alex et donc oui tu peux ajouter la version OSMC pour installer snowboy depuis jarvis :)

**Comment by alexylem** [comment]
Implémenté sur la branch `beta`. Pour le tester dès à présent:
Menu `Settings > General > Branch > beta`
Sinon attendre la mise à jour de ce weekend.
