### ISSUE TITLE
Jarvis macOSx jarvis n écoute pas les commandes

### ISSUE THREAD

**Issue by guiohms** [alexylem/jarvis#697]
Bonjour,
J ai installe jarvis comme indiqué. Je l ai appelle Alfred. Il semble écouter son nom mais n écoute pas les commandes apres. J essaye avec bonjour ou test mais rien. Le micro est le petit porte cravate conseille et il semble bien marcher. J ai la log suivante mais je n y connais pas grand chose. Pouvez vous m aider ? Je n ai pas trouvé de cas similaire
```
Mac-mini-de-Guillaume:jarvis guillaume_bourdarot$ ./jarvis.sh
Notice: you can use 'jarvis' instead of './jarvis.sh'
alfred: Hello
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
alfred: Waiting to hear 'alfred'
batman: alfred
batman: ERROR: rec command failed
HELP: retry in troubleshooting mode for more details

Mac-mini-de-Guillaume:jarvis guillaume_bourdarot$ ./jarvis.sh
Notice: you can use 'jarvis' instead of './jarvis.sh'

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              x86_64 
jv_os_name           Mac OS X 
jv_os_version        10.12.5 
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
recorder             snowboy 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           osx_say 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
alfred: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
alfred: Waiting to hear 'alfred'
batman: (listening...)
DEBUG: models=alfred
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2017-08-11 18:24:02
INFO:snowboy:Ticks status: 1 7 0 1
WARNING:snowboy:No match silence_before
INFO:snowboy:Keyword 1 detected at time: 2017-08-11 18:24:10
INFO:snowboy:Ticks status: 2 3 1 1
DEBUG: modelid=0
alfred
DEBUG: entering_cmd hook
batman: (listening...)
DEBUG: start_speaking hook ""
utils/timeout.sh 10 python  recorders/snowboy/main.py 20 /tmp/jarvis-record.wav 
Traceback (most recent call last):
  File "recorders/snowboy/main.py", line 1, in <module>
    import wavget
  File "/Users/guillaume_bourdarot/jarvis/recorders/snowboy/wavget.py", line 9, in <module>
    import snowboydecoder
  File "/Users/guillaume_bourdarot/jarvis/recorders/snowboy/../../stt_engines/snowboy/snowboydecoder.py", line 4, in <module>
    import pyaudio
ImportError: No module named pyaudio
ERROR: rec command failed
HELP: retry in troubleshooting mode for more details

DEBUG: program_exit hook
Mac-mini-de-Guillaume:jarvis guillaume_bourdarot$
```

**Comment by Oliv4945** [comment]
Salut, dans le menu audio tu peux essayer de passer le "recorder" de snowboy à sox ;-)
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by guiohms** [comment]
ca fonctionne merci. je vais créer un nouveau ticket, Jarvis ne comprend pas les commandes aide. enfin si une ou deux et il plante mais je vais voir s il y a deja eu des cas et sinon je crierai un nouveau post. celui ci est a clore. merci encore
