### ISSUE TITLE
Problème micro Webcam C510 à l'utilisation de Jarvis

### ISSUE THREAD

**Issue by SchO2n** [alexylem/jarvis#723]
### Description

Bonjour,
J'ai installé récemment jarvis sur une distribution Raspbian Stretch Lite.
L'installation se passe presque correctement sauf pour le périphérique micro qui se trouve chez moi sur une Webcam C510. Après l'installation, j'arrive tout de même à le faire fonctionner en allant dans les réglages. C'est lors du lancement de Jarvis que tout se complique. Pourriez-vous m'aider à résoudre mon problème?
Voici une copie d'un lancement en mode troubleshooting:

### Mode troubleshooting
```shell
------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Logitech, Inc. HD Webcam C510
recorder             sox
trigger_stt          snowboy
command_stt          snowboy
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
Jaevis: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Jaevis: Waiting to hear 'Jaevis'
Seb: (listening...)
DEBUG: models=jaevis
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 2, in <module>
    import maindecoder_sox as maindecoder # snowboy decoder
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 3, in <module>
    import snowboydetect
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
DEBUG: modelid=-10
ERROR: snowboy recognition failed
HELP: check error message above, if:
IOError: [Errno Invalid input device (no default output device)] -9996
  1) check your mic in Settings / Audio / Mic
  2) reboot your device
  3) report at: https://github.com/alexylem/jarvis/issues/415
IOError: [Errno Invalid sample rate] -9997
  1) check your mic in Settings / Audio / Mic
  2) try uninstalling pulseaudio
  3) try fresh OS install
  4) your mic does not support 16k sampling rate, change mic
  5) report at: https://github.com/alexylem/jarvis/issues/311
IOError: [Errno Unanticipated host error] -9999
  1) your mic is in error state, unplug/replug it
  2) report at https://github.com/alexylem/jarvis/issues/20
Other
  1) report at https://github.com/alexylem/jarvis/issues/new
```

### cat ~/.asoundrc
```shell
pcm.!default {
  type asym
   playback.pcm {
     type plug
     slave.pcm "hw:0,0"
   }
   capture.pcm {
     type plug
     slave.pcm "hw:1,0"
   }
}
```

**Comment by wikijm** [comment]
Bonjour @SchO2n

Je vois que ton hotword n'est pas correct (jaevis). 

Relance l'assistant de création du hotword et fais nous un retour :smile:

**Comment by SchO2n** [comment]
Bonjour wikijm,

oui, je l'ai vu après, et j'avais corrigé. Mais le problème est toujours là malheureusement.
Avez-vous une autre idée?
```shell
------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Logitech, Inc. HD Webcam C510
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
jarvis: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
jarvis: Waiting to hear 'jarvis'
Seb: (listening...)
DEBUG: models=jarvis
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 2, in <module>
    import maindecoder_sox as maindecoder # snowboy decoder
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 3, in <module>
    import snowboydetect
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
DEBUG: modelid=-10
ERROR: snowboy recognition failed
HELP: check error message above, if:
IOError: [Errno Invalid input device (no default output device)] -9996
  1) check your mic in Settings / Audio / Mic
  2) reboot your device
  3) report at: https://github.com/alexylem/jarvis/issues/415
IOError: [Errno Invalid sample rate] -9997
  1) check your mic in Settings / Audio / Mic
  2) try uninstalling pulseaudio
  3) try fresh OS install
  4) your mic does not support 16k sampling rate, change mic
  5) report at: https://github.com/alexylem/jarvis/issues/311
IOError: [Errno Unanticipated host error] -9999
  1) your mic is in error state, unplug/replug it
  2) report at https://github.com/alexylem/jarvis/issues/20
Other
  1) report at https://github.com/alexylem/jarvis/issues/new

DEBUG: program_exit hook
```
