### ISSUE TITLE
snowboydetect.py ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by tbozo** [alexylem/jarvis#755]
### Description
Install sur RaspberryPi RASPBIAN STRETCH avec un Jabra 410 (modifs faites pour que l'enregistrement et le replay passe bien)
J'ai recupere mon fichier sur le site de snowboy et mis ou stipule dans la doc , au lancement j'ai 
```
ERROR: personal model for 'hey_jarvis' not found
HELP: Train 'heyjarvis.pmdl' in:
...
```

Apres l'entrainement ca plante direct
```
DEBUG: models=heyjarvis
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 2, in <module>
    import maindecoder_sox as maindecoder # snowboy decoder
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 3, in <module>
    import snowboydetect
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
```

### Logs
```shell
pi@raspberrypi:~/jarvis/stt_engines/snowboy/resources $ jarvis
cat: /proc/asound/cardb/id: No such file or directory

------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv6l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw              jabbra
rec_hw               hw:1,0
speaker
microphone           GN Netcom
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
hey_jarvis: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
hey_jarvis: Waiting to hear 'hey_jarvis'
Greg: (listening...)

ERROR: personal model for 'hey_jarvis' not found
HELP: Train 'heyjarvis.pmdl' in:
HELP: Settings > Voice Recognition > Snowboy settings > Train
HELP: Or change your hotword to default model 'snowboy' in:
HELP: Settings > General > Magic word

DEBUG: program_exit hook
pi@raspberrypi:~/jarvis/stt_engines/snowboy/resources $ jarvis

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.58 [00:00:00.00] Out:49.2k [      |      ]        Clip:0    ^C
Aborted.

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.07 [00:00:00.00] Out:41.0k [      |      ]        Clip:0    ^C
Aborted.

Input File     : 'default' (alsa)
Channels       : 1
Sample Rate    : 16000
Precision      : 16-bit
Sample Encoding: 16-bit Signed Integer PCM

In:0.00% 00:00:03.58 [00:00:00.00] Out:49.2k [      |      ]        Clip:0    ^C
Aborted.
Training model...
######################################################################## 100.0%
Completed
cat: /proc/asound/cardb/id: No such file or directory

------------ Config ------------
jv_branch            master
jv_version
jv_arch              armv6l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw              jabbra
rec_hw               hw:1,0
speaker
microphone           GN Netcom
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook
hey_jarvis: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
hey_jarvis: Waiting to hear 'hey_jarvis'
Greg: (listening...)
DEBUG: models=heyjarvis
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 2, in <module>
    import maindecoder_sox as maindecoder # snowboy decoder
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 3, in <module>
    import snowboydetect
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
DEBUG: modelid=-10
ERROR: snowboy recognition failed
HELP: check error message above, if:
IOError: [Errno Invalid input device (no default output device)] -9996
  1) check your mic in Settings / Audio / Mic
  2) reboot your device
  3) report at: https://github.com/alexylem/jarvis/issues/415
IOError: [Errno Invalid sample rate] -9997
  1) check your mic in Settings / Audio / Mic
  2) try uninstalling pulseaudio
  3) try fresh OS install
  4) your mic does not support 16k sampling rate, change mic
  5) report at: https://github.com/alexylem/jarvis/issues/311
IOError: [Errno Unanticipated host error] -9999
  1) your mic is in error state, unplug/replug it
  2) report at https://github.com/alexylem/jarvis/issues/20
Other
  1) report at https://github.com/alexylem/jarvis/issues/new
```

**Comment by Oliv4945** [comment]
oops, il ne fait pas bon essayer de répondre au réveil. Il ne manque pas Python mais le module Snowboy.

Je n'ai pas mon instance Jarvis sous la main, donc on va tatoner un peu :)
Que donne `ls -al stt_engines/snowboy/` dans le répertoire de Jarvis ?

**Comment by tbozo** [comment]
On a bien le .so
```
pi@raspberrypi:~/jarvis $ ls -al stt_engines/snowboy/
total 780
drwxr-xr-x 3 pi pi   4096 Nov 24 21:21 .
drwxr-xr-x 7 pi pi   4096 Nov 24 20:40 ..
-rw-r--r-- 1 pi pi  10478 Nov 24 20:40 maindecoder.py
-rw-r--r-- 1 pi pi  11375 Nov 24 20:40 maindecoder_sox.py
-rw-r--r-- 1 pi pi   9508 Nov 24 21:21 maindecoder_sox.pyc
-rw-r--r-- 1 pi pi   3106 Nov 24 20:40 main.py
-rw-r--r-- 1 pi pi  11586 Nov 24 20:40 main.sh
drwxr-xr-x 2 pi pi   4096 Nov 29 07:40 resources
-rw-r--r-- 1 pi pi   6824 Nov 24 20:51 snowboydecoder.py
-rw-r--r-- 1 pi pi   4265 Nov 24 20:51 snowboydetect.py
-rw-r--r-- 1 pi pi   6179 Nov 24 21:21 snowboydetect.pyc
-rwxr-xr-x 1 pi pi 701816 Sep 22  2016 _snowboydetect.so
-rwxr-xr-x 1 pi pi    264 Nov 24 20:40 uninstall.sh
```


BTW 
```
pi@raspberrypi:~/jarvis $ python -V
Python 2.7.13
```

**Comment by Oliv4945** [comment]
Salut,

S'après #338, il y a quand même un soucis d'installation Pyhton. Essaie quand même `sudo apt-get install python2.7`
Dans #716 ça a été résolu grâce à un `sudo apt-get update`

**Comment by tbozo** [comment]
Non cela n'a rien changé.
Le .so est pourtant la.
C'est un probleme snowboy avec raspbian stretch (peut etre du au changement
de la glibc)

Je suis passe sous Raspbian Jessie et tout roule

La derniere image de Raspbian Jessie se trouve ici peut etre est il
interessant de la mettre en lien et d'avertir que pour le moment stretch
est incompatible.
https://downloads.raspberrypi.org/raspbian/images/raspbian-2017-07-05/2017-07-05-raspbian-jessie.zip

A+


2017-12-03 23:09 GMT+01:00 Oliv4945 <notifications@github.com>:

**Comment by bricolgloo** [comment]
Bonjour, 
je me lance aussi sur OpenJarvis et j'ai le meme genre d'erreur
j'ai un micro bidon donc j'ai aussi des doutes la dessus 
je suis en cours de download Jessie, je reviens vers vous
w&s

**Comment by bricolgloo** [comment]
Coucou, 
sur Jessie, pas de pb 
micro pourri reconnais rien mais pas de soucis coté snowboy au lancement de Jarvis! 
Sans avoir le détail je confirme que frech stretch + openjarvis = plantage

**Comment by Oliv4945** [comment]
Salut,

ça ressemble à #338.
Est-ce que vous pouvez essayer la commande `sudo apt-get install libpython2.7` et relancer Jarvis ?

**Comment by tbozo** [comment]
Je vais essayer j'ai gardé la SD card sur laquelle j'aivais installé STRETCH.

**Comment by tbozo** [comment]
```
pi@raspberrypi:~ $ sudo apt-get install libpython2.7
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  libpython2.7
0 upgraded, 1 newly installed, 0 to remove and 5 not upgraded.
Need to get 916 kB of archives.
After this operation, 3,168 kB of additional disk space will be used.
Err:1 http://mirrordirector.raspbian.org/raspbian stretch/main armhf libpython2.7 armhf 2.7.13-2
  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/p/python2.7/libpython2.7_2.7.13-2_armhf.deb  404  Not Found [IP: 2a00:1098:0:80:1000:75:0:3 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

**Comment by Oliv4945** [comment]
@tbozo : Visiblement tu as eu un problème de connexion, réessaie.
Je viens juste de réinstaller un rPi tout frais et il faut effectivement faire `sudo apt-get install libpython2.7` pour que ça fonctionne, je vais mettre à jour Jarvis

**Comment by Oliv4945** [comment]
Je viens de retester le code que j'ai changé sur une install Rasbian Lite et ça fonctionne.
Normalement ça devrait le faire sur vos installations avec `sudo apt-get update && sudo apt-get install libpython2.7`

Dites moi si ça ne va pas chez vous je rouvre l'issue.
