### ISSUE TITLE
ERROR: snowboy recognition failed

### ISSUE THREAD

**Issue by natou31** [alexylem/jarvis#776]
Bonjour,
J'ai un problème avec  mon jarvis tout fraîchement installé sur un raspberry. Tout s'est super bien passé lors de l'installation mais voilà ce que j'ai au démarrage en mode troubleshooting.
J'arrive pas à trouver une solution.
Cdt
```
Jarvis: Waiting to hear 'Jarvis'
Monsieur: ERROR: snowboy recognition failed
HELP: run in troubleshooting mode for more information

**------------ Config ------------**
jv_branch            master
jv_version
jv_arch              armv7l
jv_os_name           raspbian
jv_os_version        9
language             fr_FR
play_hw              hw:0,0
rec_hw               hw:1,0
speaker              ALSA
microphone           Texas Instruments
recorder             sox
trigger_stt          snowboy
command_stt          bing
tts_engine           svox_pico
**--------------------------------**

DEBUG: program_startup hook
DEBUG: start_speaking hook
Jarvis: Hello
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Jarvis: Waiting to hear 'Jarvis'
Monsieur: (listening...)
DEBUG: models=jarvis
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 2, in <module>
    import maindecoder_sox as maindecoder # snowboy decoder
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 3, in <module>
    import snowboydetect
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/pi/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
ImportError: libpython2.7.so.1.0: cannot open shared object file: No such file or directory
DEBUG: modelid=-10
```

**Comment by Cqoicebordel** [comment]
Je n'en sais rien, mais à vue de nez, je dirais qu'il se plaint que Python 2.7 n'es pas installé.

**Comment by natou31** [comment]
Et comment peut-on l'installer ?

**Comment by Oliv4945** [comment]
Bonjour,

Duplication de #775. Je ferme ce sujet et on continue à discutions [là bas](https://github.com/alexylem/jarvis/issues/755#issuecomment-354756483).

Oliv'
