### ISSUE TITLE
probleme audio

### ISSUE THREAD

**Issue by Elsikan1** [alexylem/jarvis#934]
### Description

bonjour, 
je suis débutant et souhaite utiliser jarvis pour faire une sorte de domotique mais dans une voiture, bref j'ai surtout un problème d'erreur qui me bloque au début de mon projet par une erreur que je n'arrive pas a comprendre.

jarvis démarre et fonctionne parfaitement en mode clavier, mais en mode vocal il attend et me renvoi ceci (en mode debug)

### Logs
monsieur: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 90, in record_proc
    wav = wave.open(process.stdout, 'rb')
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 164, in __init__
    self.initfp(f)
  File "/usr/lib/python2.7/wave.py", line 129, in initfp
    self._file = Chunk(file, bigendian = 0)
  File "/usr/lib/python2.7/chunk.py", line 63, in __init__
    raise EOFError
EOFError

Si une âme charitable pouvais me donner au moins une piste ^^

merci

**Comment by Elsikan1** [comment]
Bonjour,
personne n'as d'info ou je n'ai pas mis assez d'info dans ma question ?

merci d'avance.

**Comment by wikijm** [comment]
Bonjour @Elsikan1,

Si tu rejoue l'assistant de configuration, est ce que tu as toujours un retour micro ?

Cordialement,
WikiJM

**Comment by Elsikan1** [comment]
Bonjour, oui le micro fonctionne toujours quand je refait le paramétrage
audio

**Comment by wikijm** [comment]
Je n'arrives pas à reproduire ton incident.
Peux-tu partager une vidéo faite avec [ASCIINEMA ](https://asciinema.org/)?

**Comment by Elsikan1** [comment]
Bonjour, et merci pour vos infos.
apres plusieurs réinstallation complete (OS + Jarvis) je n'ai plus cette erreur. par contre il ne fonctionne qu'en mode clavier.
il reconnait le Hotword "Jarvis" mais ne reconnait rien derriere.
en mode debug cela donne ça :

pi@raspberrypi:~/jarvis $ ./jarvis.sh
Notice: you can use 'jarvis' instead of './jarvis.sh'

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        9 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           Asahi Kasei Microsystems Co., Ltd  
recorder             sox 
trigger_stt          snowboy 
command_stt          bing 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook "bonjour monsieur"
jarvis: bonjour monsieur
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
jarvis: Waiting to hear 'jarvis'
monsieur: (listening...)
DEBUG: models=jarvis
INFO:snowboy:Ticks: [2, 20, 5, -1]
INFO:snowboy:Keyword 1 detected at time: 2019-05-19 01:00:08
INFO:snowboy:Ticks status: 2 5 2 1
DEBUG: modelid=0
jarvis
DEBUG: entering_cmd hook
DEBUG: start_speaking hook "oui monsieur"
jarvis: oui monsieur
DEBUG: stop_speaking hook
monsieur: (listening...)
DEBUG: start_listening hook
utils/timeout.sh 10 rec -V1 -q -r 16000 -c 1 -b 16 -e signed-integer --endian little /dev/shm/jarvis-record.wav gain 2 silence 1 0.1 0.1% 1 0.3 0.05% pad 0.5 0.5 trim 0 5
DEBUG: speech duration was 50 (10 = 1 sec)
WARNING: too long for a command (max 4 secs), ignoring...
HELP: try in order the following options
1) wait longer between voice commands
2) reduce ambiant background noise
3) decrease mic sensitivity in Settings > Audio
4) increase Min Silence Level to Stop
DEBUG: stop_listening hook 
DEBUG: program_exit hook
pi@raspberrypi:~/jarvis $ 



il ne reconnait que "Jarvis" j'ai pourtant fait sur le site de snowboy les mots que je voulais "Aide / merci / etc pour au moins tester les commande par defaut. j'ai essayé de les enregistrer directement depuis jarvis mais cela ne change rien il ne reconnait que "jarvis". 

De plus il est super long a réagir à "jarvis" et ne parle pas (aucun son de sa part) pourtant lors de la config j'entend bien les applaudissement. je patauge avec l'audio ^

**Comment by ioteecs-team** [comment]
Pour ma part, j'ai dû recompiler snowboy pour que ça fonctionne.
Pour les temps de réponse, il faut retirer tout interface graphique.

**Comment by Elsikan1** [comment]
> Pour ma part, j'ai dû recompiler snowboy pour que ça fonctionne.
> Pour les temps de réponse, il faut retirer tout interface graphique.

Merci pour ces infos, j'ai cherché mais ne vois pas comment recompiler snowboy ^^
l'interface graphique je pourrais la retiré après quand jarvis sera fonctionnel ou je dois réinstaller un raspbian sans interface ?
