### ISSUE TITLE
archlinux support

### ISSUE THREAD

**Issue by Paullux** [alexylem/jarvis#940]
### Description

Permettre l'installation sur Archlinux pour gérer un pc sous Arch.

**Comment by Paullux** [comment]
J'ai commencé à faire deux trois modifications à la main pour le faire fonctionner, mais je but sur snowboy : 
 paul  ~  jarvis  ./jarvis.sh 
Notice: you can use 'jarvis' instead of './jarvis.sh'

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              x86_64 
jv_os_name           manjaro 
jv_os_version         
language             fr_FR 
play_hw              false 
rec_hw               false 
speaker              Default 
microphone           Default 
recorder             sox 
trigger_stt          snowboy 
command_stt          google 
tts_engine           google 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook "Hello"
Jarvis: Hello
DEBUG: using cache /dev/shm/hello.mp3
DEBUG: stop_speaking hook
User defined commands:
*AIDE*                  *BONJOUR*|*SALUT*       *COMMENT*APPELLE*
*MERCI*                 *AU REVOIR*|*BYE*       ANNULE*|TERMINE*
ENCORE*                 *TEST*                  *VERSION*
*REPETE (*) ET (*)      *CA VA*                 >*OUI*
>*NON*|*PAS*
Jarvis: Waiting to hear 'Jarvis'
paul: (listening...)
DEBUG: models=jarvis
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 2, in <module>
    import maindecoder_sox as maindecoder # snowboy decoder
  File "/home/paul/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 3, in <module>
    import snowboydetect
  File "/home/paul/jarvis/stt_engines/snowboy/snowboydetect.py", line 28, in <module>
    _snowboydetect = swig_import_helper()
  File "/home/paul/jarvis/stt_engines/snowboy/snowboydetect.py", line 24, in swig_import_helper
    _mod = imp.load_module('_snowboydetect', fp, pathname, description)
  File "/usr/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dynamic module does not define module export function (PyInit__snowboydetect)
DEBUG: modelid=-10
ERROR: snowboy recognition failed
HELP: check error message above, if:
IOError: [Errno Invalid input device (no default output device)] -9996
  1) check your mic in Settings / Audio / Mic
  2) reboot your device
  3) report at: https://github.com/alexylem/jarvis/issues/415
IOError: [Errno Invalid sample rate] -9997
  1) check your mic in Settings / Audio / Mic
  2) try uninstalling pulseaudio
  3) try fresh OS install
  4) your mic does not support 16k sampling rate, change mic
  5) report at: https://github.com/alexylem/jarvis/issues/311
IOError: [Errno Unanticipated host error] -9999
  1) your mic is in error state, unplug/replug it
  2) report at https://github.com/alexylem/jarvis/issues/20
Other
  1) report at https://github.com/alexylem/jarvis/issues/new

DEBUG: program_exit hook

**Comment by Roger-T800** [comment]
I am a few steps behind. How did you pass the libsox-fmt-mp3 thing? There is no such dependency in Manjaro.
