### ISSUE TITLE
ERROR: snowboy recognition failed

### ISSUE THREAD

**Issue by grangec** [alexylem/jarvis#951]
Bonjour,
Premier Jarvis fraichement installé sur raspberry4 4Go.
Haut parleur bluetooth et micro USB reconnus et paramétrés.
Souhait de fonctionnement meme sans connexion internet, donc choix de snowboy integrale.
Au demarrage, Jarvis ecoute quelques instant puis sort ainsi : 
```
pi@raspberrypi:~/jarvis $ ./jarvis.sh 
Notice: you can use 'jarvis' instead of './jarvis.sh'

------------ Config ------------
jv_branch            master 
jv_version            
jv_arch              armv7l 
jv_os_name           raspbian 
jv_os_version        10 
language             fr_FR 
play_hw              hw:0,0 
rec_hw               hw:1,0 
speaker              ALSA 
microphone           C-Media Electronics, Inc.  
recorder             snowboy 
trigger_stt          snowboy 
command_stt          snowboy 
tts_engine           svox_pico 
--------------------------------

DEBUG: program_startup hook
DEBUG: start_speaking hook "Bonjour"
jarvis: Bonjour
DEBUG: stop_speaking hook
User defined commands:
*AIDE*			*BONJOUR*|*SALUT*	*COMMENT*APPELLE*
*MERCI*			*AU REVOIR*|*BYE*	ANNULE*|TERMINE*
ENCORE*			*TEST*			*VERSION*
*REPETE (*) ET (*)	*CA VA*			>*OUI*
>*NON*|*PAS*
Commands from plugin jarvis-domoticz:
*ALLUM[^ ]+ (*)		*ETEIN[^ ]+ (*)		*FERME (*)
*OUVRE (*)		*QUEL*ETAT* (*)|*DONNE* *COMBIEN*DEGREE*FAIT* (
jarvis: Waiting to hear 'jarvis'
cyrille: (listening...)
DEBUG: models=jarvis
Traceback (most recent call last):
  File "stt_engines/snowboy/main.py", line 2, in <module>
    import maindecoder_sox as maindecoder # snowboy decoder
  File "/home/pi/jarvis/stt_engines/snowboy/maindecoder_sox.py", line 166
    logger.info("Ticks status: " + `silence_before` + " " +
                                   ^
SyntaxError: invalid syntax
DEBUG: modelid=-10
ERROR: snowboy recognition failed
HELP: check error message above, if:
IOError: [Errno Invalid input device (no default output device)] -9996
  1) check your mic in Settings / Audio / Mic
  2) reboot your device
  3) report at: https://github.com/alexylem/jarvis/issues/415
IOError: [Errno Invalid sample rate] -9997
  1) check your mic in Settings / Audio / Mic
  2) try uninstalling pulseaudio
  3) try fresh OS install
  4) your mic does not support 16k sampling rate, change mic
  5) report at: https://github.com/alexylem/jarvis/issues/311
IOError: [Errno Unanticipated host error] -9999
  1) your mic is in error state, unplug/replug it
  2) report at https://github.com/alexylem/jarvis/issues/20
Other
  1) report at https://github.com/alexylem/jarvis/issues/new

DEBUG: program_exit hook
```
J'avoue ne pas avoir encore creusé profondément pour trouver une solution, mais je cré quand même le ticket ne serais ce que pour eventuellement créer un précédent.
En attendant, si vous avez une idée, merci par avance.

**Comment by grangec** [comment]
Solution : Changer de version de Python et passer vers la 2.7
En l'occurence, dans mon cas, dire au système d'utiliser la 2.7 comme ceci :
```
pi@raspberrypi:~/jarvis $ sudo update-alternatives --config python
Il existe 2 choix pour l'alternative python (qui fournit /usr/bin/python).

  Sélection   Chemin              Priorité  État
------------------------------------------------------------
* 0            /usr/bin/python3.7   2         mode automatique
  1            /usr/bin/python2.7   1         mode manuel
  2            /usr/bin/python3.7   2         mode manuel

Appuyez sur <Entrée> pour conserver la valeur par défaut[*] ou choisissez le numéro sélectionné :1
update-alternatives: utilisation de « /usr/bin/python2.7 » pour fournir « /usr/bin/python » (python) en mode manuel
```

**Comment by satana888** [comment]
Bonjour,
Une question que je me pose, étant donné que jarvis tourne avec du python 2.7 comment sa se passera en janvier 2020 car  on va vers le python 3 ... ????????

**Comment by grangec** [comment]
On migrera le code.

**Comment by EtienneAr** [comment]
Bonjour, 

Où en est le passage du code de Python2 à Python3 ?
J'essayes d'installer Jarvis sur Ubuntu 20.04 n'ayant que Python3 de pré installé.
(Et j'avoue que je n'ai pas franchement envie d'installer python2...)
